export default [
  'Action',
  'Adventure',
  'Battle royale',
  "Beat 'em all",
  'Card game',
  'Educational',
  'Eroge',
  'Fighting',
  'J-RPG',
  'Monster tamer',
  'Metroidvania',
  'Point and click',
  'Platformer',
  'Puzzle',
  'Racing',
  'Rhythm',
  'Romance',
  'Roguelike',
  'RPG',
  'Sandbox',
  'Shooter',
  'Simulation',
  'Sports',
  'Stealth',
  'Strategy',
  'Survival',
  'Survival horror',
  'Text-based',
  'Visual novel',
]
